// @formilyjs/antd https://antd.formilyjs.org/zh-CN/components
import {
  FormButtonGroup,
  Reset,
  Checkbox,
  TimePicker,
  Transfer,
  Switch,
  ArrayCards,
  ArrayTable,
  ArrayItems,
  Input,
  NumberPicker,
  Password,
  Radio,
  Upload,
  Select,
  SelectTable,
  Space,
  TreeSelect,
  FormTab,
  FormStep,
  FormLayout,
  FormItem,
  FormGrid,
  FormDrawer,
  FormDialog,
  FormCollapse,
  Cascader,
  Editable,
} from '@apps/form'

import { Button, Row, DatePicker } from '@linkseeks/ui'

import {
  // CustomUpload,
  CustomStatus,
  CustomAddArray,
  CustomSlider,
  CustomRadio,
  Search,
  CustomInputSearch,
  CustomCategorySearch,
  CardCheckBox,
  SingleSelect,
  MultTable,
  Children,
  CircleBox,
  Phone,
  SearchSelect,
  TableTagList,
  DateSelect,
  DateRangePickerUnix,
  SmilingFace,
  // FixUpload,
  Submit,
  Text,
} from './components'

import layout from './layout'

interface IComponent {
  [key: string]: any
}

const componentExport: IComponent = {
  //from @apps/form @formilyjs/antd
  FormButtonGroup,
  Reset,
  Checkbox,
  TimePicker,
  Transfer,
  Switch,
  ArrayCards,
  ArrayTable,
  ArrayItems,
  Input,
  NumberPicker,
  Password,
  Radio,
  Upload,
  Select,
  SelectTable,
  Space,
  TreeSelect,
  FormTab,
  FormStep,
  FormLayout,
  FormItem,
  FormGrid,
  FormDrawer,
  FormDialog,
  FormCollapse,
  Cascader,
  Editable,

  // from @linkseeks/ui antd@4.2
  Button,
  Row,
  DatePicker,

  // layout
  ...layout,

  // @todo custom组件 需要用到再打开,需对组件改造为form2.0 用法
  CheckboxSingle: Checkbox,
  // CustomUpload,
  CustomStatus,
  CustomAddArray,
  CustomSlider,
  CustomRadio,
  Search,
  CustomInputSearch,
  CustomCategorySearch,
  Submit,
  Text,
  CardCheckBox,
  MultTable,
  Children,
  CircleBox,
  SchemaFormButtonGroup: FormButtonGroup,
  SchemaButton: Button,
  schemaSubmit: Submit,
  schemaReset: Reset,
  FlexBox: Row,
  Phone,
  SingleSelect,
  SearchSelect,
  DateRangePicker: DatePicker.RangePicker,
  TableTagList,
  DateSelect,
  DateRangePickerUnix,
  SmilingFace,
  // FixUpload,

  // setup start
  time: TimePicker,
  timerange: TimePicker.RangePicker,
  transfer: Transfer,
  boolean: Switch,
  array: ArrayCards,
  cards: ArrayCards,
  table: ArrayTable,
  checkbox: Checkbox.Group,
  date: DatePicker,
  daterange: DatePicker.RangePicker,
  year: DatePicker.YearPicker,
  month: DatePicker.MonthPicker,
  week: DatePicker.WeekPicker,
  string: Input,
  textarea: Input.TextArea,
  number: NumberPicker,
  password: Password,
  radio: Radio.Group,
  // range: Range,
  // @todo formily 1.0的高阶组件 以后再补上
  // rating: Rating,
  upload: Upload,
  // setup end
}

export default componentExport
