/*
 * @Author: XieZhiXiong
 * @Date: 2020-12-18 11:20:26
 * @LastEditors: XieZhiXiong
 * @LastEditTime: 2020-12-18 11:20:27
 * @Description:
 */
import {
  EXCHANGE_OUTER_STATUS_UNCOMMITTED,
  EXCHANGE_OUTER_UNCONFIRMED,
  EXCHANGE_OUTER_STATUS_FAILED,
  EXCHANGE_OUTER_STATUS_SUCCESS,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  EXCHANGE_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  EXCHANGE_OUTER_STATUS_RETURN_DELIVERY,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE,
  EXCHANGE_OUTER_STATUS_RETURN_RECEIVE,
  EXCHANGE_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_DELIVERY,
  EXCHANGE_OUTER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS,
  EXCHANGE_OUTER_STATUS_REPLACE_DELIVERY,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_STORAGE,
  EXCHANGE_OUTER_STATUS_REPLACE_RECEIVE,
  EXCHANGE_OUTER_STATUS_UNCONFIRMED_REPLACE_RECEIPT,
  EXCHANGE_OUTER_STATUS_UNCONFIRMED_FINISHED,
  EXCHANGE_OUTER_STATUS_FINISHED,
  EXCHANGE_INNER_STATUS_UNCOMMITTED,
  EXCHANGE_INNER_STATUS_COMMIT_SUCCESS,
  EXCHANGE_INNER_STATUS_SUCCESS_1,
  EXCHANGE_INNER_STATUS_SUCCESS_2,
  EXCHANGE_INNER_STATUS_FAILED,
  EXCHANGE_INNER_STATUS_CONFIRM_SUCCESS,
  EXCHANGE_INNER_STATUS_CONFIRM_FAILED,
  EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY,
  EXCHANGE_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  EXCHANGE_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY,
  EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_STORAGE,
  EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_STORAGE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_DELIVERY,
  EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_DELIVERY,
  EXCHANGE_INNER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS,
  EXCHANGE_INNER_STATUS_SUPPLIER_UNCONFIRMED_LOGISTICS,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_DELIVERY,
  EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_STORAGE,
  EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_STORAGE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIVE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIPT,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_FINISHED,
  EXCHANGE_INNER_STATUS_FINISHED,
  EXCHANGE_INNER_STATUS_UNACCEPTED_RETURN_LOGISTICS,
  EXCHANGE_INNER_STATUS_UNACCEPTED_RETURN_EXCHANGE,
  EXCHANGE_INNER_STATUS_COMMIT_FAILED,
  EXCHANGE_INNER_STATUS_FAILED_1,
  EXCHANGE_INNER_STATUS_FAILED_2,
} from '@/constants'

// 售后换货外部状态 StatusTag map
export const EXCHANGE_OUTER_STATUS_TAG_MAP = {
  [EXCHANGE_OUTER_STATUS_UNCOMMITTED]: 'default',
  [EXCHANGE_OUTER_UNCONFIRMED]: 'primary',
  [EXCHANGE_OUTER_STATUS_FAILED]: 'danger',
  [EXCHANGE_OUTER_STATUS_SUCCESS]: 'primary',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY]: 'danger',
  [EXCHANGE_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: 'warning',
  [EXCHANGE_OUTER_STATUS_RETURN_DELIVERY]: 'danger',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE]: 'danger',
  [EXCHANGE_OUTER_STATUS_RETURN_RECEIVE]: 'danger',
  [EXCHANGE_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: 'danger',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_DELIVERY]: 'nobility',
  [EXCHANGE_OUTER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS]: 'success',
  [EXCHANGE_OUTER_STATUS_REPLACE_DELIVERY]: 'nobility',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_STORAGE]: 'nobility',
  [EXCHANGE_OUTER_STATUS_REPLACE_RECEIVE]: 'nobility',
  [EXCHANGE_OUTER_STATUS_UNCONFIRMED_REPLACE_RECEIPT]: 'primary',
  [EXCHANGE_OUTER_STATUS_UNCONFIRMED_FINISHED]: 'primary',
  [EXCHANGE_OUTER_STATUS_FINISHED]: 'success',
}

// 售后换货内部状态 Badge map
export const EXCHANGE_INNER_STATUS_BADGE_MAP = {
  [EXCHANGE_INNER_STATUS_UNCOMMITTED]: '#669EDE',
  [EXCHANGE_INNER_STATUS_COMMIT_SUCCESS]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_SUCCESS_1]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_SUCCESS_2]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_FAILED]: '#EF6260',
  [EXCHANGE_INNER_STATUS_CONFIRM_SUCCESS]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_CONFIRM_FAILED]: '#EF6260',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY]: '#FF991F',
  [EXCHANGE_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_STORAGE]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_STORAGE]: '#FF991F',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_DELIVERY]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_DELIVERY]: '#FF991F',
  [EXCHANGE_INNER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_SUPPLIER_UNCONFIRMED_LOGISTICS]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_DELIVERY]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_STORAGE]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_STORAGE]: '#FF991F',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIVE]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIPT]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_FINISHED]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_FINISHED]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_UNACCEPTED_RETURN_LOGISTICS]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNACCEPTED_RETURN_EXCHANGE]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_COMMIT_FAILED]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_FAILED_1]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_FAILED_2]: '#E63F3B',
}

// 退货明细内部状态
/**
 * 未确认发货
 */
export const MAIL_INNER_STATUS_UNCONFIRMED_DELIVER = 1
/**
 * 已确认发货
 */
export const MAIL_INNER_STATUS_CONFIRMED_DELIVER = 2
/**
 * 已确认收货
 */
export const MAIL_INNER_STATUS_CONFIRMED_RECEIVING = 3
/**
 * 确认回单
 */
export const MAIL_INNER_STATUS_CONFIRMED_BACK = 4
