/*
 * @Author: XieZhiXiong
 * @Date: 2020-12-18 14:33:05
 * @LastEditors: XieZhiXiong
 * @LastEditTime: 2021-02-02 09:58:08
 * @Description:
 */
import {
  RETURN_INNER_STATUS_UNCOMMITTED,
  RETURN_INNER_STATUS_COMMIT_SUCCESS,
  RETURN_INNER_STATUS_SUCCESS_1,
  RETURN_INNER_STATUS_SUCCESS_2,
  RETURN_INNER_STATUS_FAILED_2,
  RETURN_INNER_STATUS_CONFIRM_SUCCESS,
  RETURN_INNER_STATUS_CONFIRM_FAILED,
  RETURN_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  RETURN_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY,
  RETURN_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  RETURN_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS,
  RETURN_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY,
  RETURN_INNER_STATUS_NOT_ADDED_RETURN_STORAGE,
  RETURN_INNER_STATUS_UNREVIEWED_RETURN_STORAGE,
  RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE,
  RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  RETURN_INNER_STATUS_TO_BE_REFUNDED,
  RETURN_INNER_STATUS_UNCONFIRMED_REFUNDED,
  RETURN_INNER_STATUS_REFUNDED_FAIL,
  RETURN_INNER_STATUS_REFUNDED_SUCCESS,
  RETURN_INNER_STATUS_UNCONFIRMED_FINISHED,
  RETURN_INNER_STATUS_FINISHED,
  RETURN_INNER_STATUS_UNACCEPTED_LOGISTICS,
  RETURN_INNER_STATUS_COMMIT_FAILED,
  RETURN_INNER_STATUS_FAILED_1,
  RETURN_OUTER_STATUS_UNCOMMITTED,
  RETURN_OUTER_UNCONFIRMED,
  RETURN_OUTER_STATUS_FAILED,
  RETURN_OUTER_STATUS_SUCCESS,
  RETURN_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  RETURN_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  RETURN_OUTER_STATUS_RETURN_DELIVERY,
  RETURN_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE,
  RETURN_OUTER_STATUS_RETURN_RECEIVE,
  RETURN_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  RETURN_OUTER_STATUS_TO_BE_REFUNDED,
  RETURN_OUTER_STATUS_UNCONFIRMED_REFUNDED,
  RETURN_OUTER_STATUS_NOT_RECEIVED,
  RETURN_OUTER_STATUS_UNCONFIRMED_FINISHED,
  RETURN_OUTER_STATUS_FINISHED,
} from '@/constants'

// 退货明细内部状态
/**
 * 未确认发货
 */
export const MAIL_INNER_STATUS_UNCONFIRMED_DELIVER = 1
/**
 * 已确认发货
 */
export const MAIL_INNER_STATUS_CONFIRMED_DELIVER = 2
/**
 * 已确认收货
 */
export const MAIL_INNER_STATUS_CONFIRMED_RECEIVING = 3
/**
 * 确认回单
 */
export const MAIL_INNER_STATUS_CONFIRMED_BACK = 4

// 售后退货外部状态 StatusTag map
export const RETURN_OUTER_STATUS_TAG_MAP = {
  [RETURN_OUTER_STATUS_UNCOMMITTED]: 'default',
  [RETURN_OUTER_UNCONFIRMED]: 'primary',
  [RETURN_OUTER_STATUS_FAILED]: 'danger',
  [RETURN_OUTER_STATUS_SUCCESS]: 'primary',
  [RETURN_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY]: 'danger',
  [RETURN_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: 'warning',
  [RETURN_OUTER_STATUS_RETURN_DELIVERY]: 'danger',
  [RETURN_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE]: 'danger',
  [RETURN_OUTER_STATUS_RETURN_RECEIVE]: 'danger',
  [RETURN_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: 'danger',
  [RETURN_OUTER_STATUS_TO_BE_REFUNDED]: 'danger',
  [RETURN_OUTER_STATUS_UNCONFIRMED_REFUNDED]: 'primary',
  [RETURN_OUTER_STATUS_NOT_RECEIVED]: 'warning',
  [RETURN_OUTER_STATUS_UNCONFIRMED_FINISHED]: 'primary',
  [RETURN_OUTER_STATUS_FINISHED]: 'success',
}

// 售后退货内部状态 Badge map
export const RETURN_INNER_STATUS_BADGE_MAP = {
  [RETURN_INNER_STATUS_UNCOMMITTED]: '#669EDE',
  [RETURN_INNER_STATUS_COMMIT_SUCCESS]: '#41CC9E',
  [RETURN_INNER_STATUS_SUCCESS_1]: '#41CC9E',
  [RETURN_INNER_STATUS_SUCCESS_2]: '#41CC9E',
  [RETURN_INNER_STATUS_FAILED_2]: '#EF6260',
  [RETURN_INNER_STATUS_CONFIRM_SUCCESS]: '#41CC9E',
  [RETURN_INNER_STATUS_CONFIRM_FAILED]: '#EF6260',
  [RETURN_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY]: '#E63F3B',
  [RETURN_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY]: '#FF991F',
  [RETURN_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: '#E63F3B',
  [RETURN_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS]: '#6C9CEB',
  [RETURN_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY]: '#6C9CEB',
  [RETURN_INNER_STATUS_NOT_ADDED_RETURN_STORAGE]: '#E63F3B',
  [RETURN_INNER_STATUS_UNREVIEWED_RETURN_STORAGE]: '#FF991F',
  [RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE]: '#6C9CEB',
  [RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: '#6C9CEB',
  [RETURN_INNER_STATUS_TO_BE_REFUNDED]: '#E63F3B',
  [RETURN_INNER_STATUS_UNCONFIRMED_REFUNDED]: '#6C9CEB',
  [RETURN_INNER_STATUS_REFUNDED_FAIL]: '#EF6260',
  [RETURN_INNER_STATUS_REFUNDED_SUCCESS]: '#41CC9E',
  [RETURN_INNER_STATUS_UNCONFIRMED_FINISHED]: '#6C9CEB',
  [RETURN_INNER_STATUS_FINISHED]: '#41CC9E',
  [RETURN_INNER_STATUS_UNACCEPTED_LOGISTICS]: '#E63F3B',
  [RETURN_INNER_STATUS_COMMIT_FAILED]: '#E63F3B',
  [RETURN_INNER_STATUS_FAILED_1]: '#E63F3B',
}

// 退款内部状态
/**
 * 未退款
 */
export const REFUND_INNER_STATUS_NO_REFUND = 1
/**
 * 退款失败
 */
export const REFUND_INNER_STATUS_REFUND_FAILED = 2
/**
 * 退款成功
 */
export const REFUND_INNER_STATUS_REFUND_SUCCESS = 3

// 退款外部状态
/**
 * 未退款
 */
export const REFUND_OUTER_STATUS_NO_REFUND = 1
/**
 * 待确认退款
 */
export const REFUND_OUTER_STATUS_UNCONFIRMED_REFUND = 2
/**
 * 退款未到账
 */
export const REFUND_OUTER_STATUS_NOT_RECEIVED = 3
/**
 * 退款到账
 */
export const REFUND_OUTER_STATUS_RECEIVED = 4

// 退款外部状态 StatusTag map
export const REFUND_OUTER_STATUS_TAG_MAP = {
  [REFUND_OUTER_STATUS_NO_REFUND]: 'danger',
  [REFUND_OUTER_STATUS_UNCONFIRMED_REFUND]: 'primary',
  [REFUND_OUTER_STATUS_NOT_RECEIVED]: 'warning',
  [REFUND_OUTER_STATUS_RECEIVED]: 'success',
}
