import {
  REPAIR_OUTER_STATUS_UNCOMMITTED,
  REPAIR_OUTER_STATUS_UNCONFIRMED,
  REPAIR_OUTER_STATUS_FAILED,
  REPAIR_OUTER_STATUS_SUCCESS,
  REPAIR_OUTER_STATUS_FINISHED,
  REPAIR_INNER_STATUS_UNCOMMITTED,
  REPAIR_INNER_STATUS_COMMIT_SUCCESS,
  REPAIR_INNER_STATUS_SUCCESS_1,
  REPAIR_INNER_STATUS_SUCCESS_2,
  REPAIR_INNER_STATUS_FAILED_2,
  REPAIR_INNER_STATUS_CONFIRM_SUCCESS,
  REPAIR_INNER_STATUS_CONFIRM_FAILED,
  REPAIR_INNER_STATUS_FINISHED,
  EXCHANGE_OUTER_STATUS_UNCOMMITTED,
  EXCHANGE_OUTER_UNCONFIRMED,
  EXCHANGE_OUTER_STATUS_FAILED,
  EXCHANGE_OUTER_STATUS_SUCCESS,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  EXCHANGE_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  EXCHANGE_OUTER_STATUS_RETURN_DELIVERY,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE,
  EXCHANGE_OUTER_STATUS_RETURN_RECEIVE,
  EXCHANGE_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_DELIVERY,
  EXCHANGE_OUTER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS,
  EXCHANGE_OUTER_STATUS_REPLACE_DELIVERY,
  EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_STORAGE,
  EXCHANGE_OUTER_STATUS_REPLACE_RECEIVE,
  EXCHANGE_OUTER_STATUS_UNCONFIRMED_REPLACE_RECEIPT,
  EXCHANGE_OUTER_STATUS_UNCONFIRMED_FINISHED,
  EXCHANGE_OUTER_STATUS_FINISHED,
  EXCHANGE_INNER_STATUS_UNCOMMITTED,
  EXCHANGE_INNER_STATUS_COMMIT_SUCCESS,
  EXCHANGE_INNER_STATUS_SUCCESS_1,
  EXCHANGE_INNER_STATUS_SUCCESS_2,
  EXCHANGE_INNER_STATUS_FAILED,
  EXCHANGE_INNER_STATUS_CONFIRM_SUCCESS,
  EXCHANGE_INNER_STATUS_CONFIRM_FAILED,
  EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY,
  EXCHANGE_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  EXCHANGE_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY,
  EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_STORAGE,
  EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_STORAGE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_DELIVERY,
  EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_DELIVERY,
  EXCHANGE_INNER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS,
  EXCHANGE_INNER_STATUS_SUPPLIER_UNCONFIRMED_LOGISTICS,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_DELIVERY,
  EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_STORAGE,
  EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_STORAGE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIVE,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIPT,
  EXCHANGE_INNER_STATUS_UNCONFIRMED_FINISHED,
  EXCHANGE_INNER_STATUS_FINISHED,
  RETURN_INNER_STATUS_UNCOMMITTED,
  RETURN_INNER_STATUS_COMMIT_SUCCESS,
  RETURN_INNER_STATUS_SUCCESS_1,
  RETURN_INNER_STATUS_SUCCESS_2,
  RETURN_INNER_STATUS_FAILED_2,
  RETURN_INNER_STATUS_CONFIRM_SUCCESS,
  RETURN_INNER_STATUS_CONFIRM_FAILED,
  RETURN_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  RETURN_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY,
  RETURN_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  RETURN_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS,
  RETURN_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY,
  RETURN_INNER_STATUS_NOT_ADDED_RETURN_STORAGE,
  RETURN_INNER_STATUS_UNREVIEWED_RETURN_STORAGE,
  RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE,
  RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  RETURN_INNER_STATUS_TO_BE_REFUNDED,
  RETURN_INNER_STATUS_UNCONFIRMED_REFUNDED,
  RETURN_INNER_STATUS_REFUNDED_FAIL,
  RETURN_INNER_STATUS_REFUNDED_SUCCESS,
  RETURN_INNER_STATUS_UNCONFIRMED_FINISHED,
  RETURN_INNER_STATUS_FINISHED,
  RETURN_OUTER_STATUS_UNCOMMITTED,
  RETURN_OUTER_UNCONFIRMED,
  RETURN_OUTER_STATUS_FAILED,
  RETURN_OUTER_STATUS_SUCCESS,
  RETURN_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY,
  RETURN_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS,
  RETURN_OUTER_STATUS_RETURN_DELIVERY,
  RETURN_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE,
  RETURN_OUTER_STATUS_RETURN_RECEIVE,
  RETURN_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT,
  RETURN_OUTER_STATUS_TO_BE_REFUNDED,
  RETURN_OUTER_STATUS_UNCONFIRMED_REFUNDED,
  RETURN_OUTER_STATUS_NOT_RECEIVED,
  RETURN_OUTER_STATUS_UNCONFIRMED_FINISHED,
  RETURN_OUTER_STATUS_FINISHED,
} from '@/constants/afterService'

// 售后维修外部状态 StatusTag map
export const REPAIR_OUTER_STATUS_TAG_MAP = {
  [REPAIR_OUTER_STATUS_UNCOMMITTED]: 'default',
  [REPAIR_OUTER_STATUS_UNCONFIRMED]: 'success',
  [REPAIR_OUTER_STATUS_FAILED]: 'danger',
  [REPAIR_OUTER_STATUS_SUCCESS]: 'primary',
  [REPAIR_OUTER_STATUS_FINISHED]: 'success',
}

// 售后维修内部部状态 Badge map
export const REPAIR_INNER_STATUS_BADGE_MAP = {
  [REPAIR_INNER_STATUS_UNCOMMITTED]: '#669EDE',
  [REPAIR_INNER_STATUS_COMMIT_SUCCESS]: '#41CC9E',
  [REPAIR_INNER_STATUS_SUCCESS_1]: '#41CC9E',
  [REPAIR_INNER_STATUS_SUCCESS_2]: '#41CC9E',
  [REPAIR_INNER_STATUS_FAILED_2]: '#EF6260',
  [REPAIR_INNER_STATUS_CONFIRM_SUCCESS]: '#6C9CEB',
  [REPAIR_INNER_STATUS_CONFIRM_FAILED]: '#EF6260',
  [REPAIR_INNER_STATUS_FINISHED]: '#41CC9E',
}

// 售后换货外部状态 StatusTag map
export const EXCHANGE_OUTER_STATUS_TAG_MAP = {
  [EXCHANGE_OUTER_STATUS_UNCOMMITTED]: 'default',
  [EXCHANGE_OUTER_UNCONFIRMED]: 'primary',
  [EXCHANGE_OUTER_STATUS_FAILED]: 'danger',
  [EXCHANGE_OUTER_STATUS_SUCCESS]: 'primary',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY]: 'danger',
  [EXCHANGE_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: 'warning',
  [EXCHANGE_OUTER_STATUS_RETURN_DELIVERY]: 'danger',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE]: 'danger',
  [EXCHANGE_OUTER_STATUS_RETURN_RECEIVE]: 'danger',
  [EXCHANGE_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: 'danger',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_DELIVERY]: 'nobility',
  [EXCHANGE_OUTER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS]: 'success',
  [EXCHANGE_OUTER_STATUS_REPLACE_DELIVERY]: 'nobility',
  [EXCHANGE_OUTER_STATUS_NOT_ADDED_REPLACE_STORAGE]: 'nobility',
  [EXCHANGE_OUTER_STATUS_REPLACE_RECEIVE]: 'nobility',
  [EXCHANGE_OUTER_STATUS_UNCONFIRMED_REPLACE_RECEIPT]: 'primary',
  [EXCHANGE_OUTER_STATUS_UNCONFIRMED_FINISHED]: 'primary',
  [EXCHANGE_OUTER_STATUS_FINISHED]: 'success',
}

// 售后换货内部状态 Badge map
export const EXCHANGE_INNER_STATUS_BADGE_MAP = {
  [EXCHANGE_INNER_STATUS_UNCOMMITTED]: '#669EDE',
  [EXCHANGE_INNER_STATUS_COMMIT_SUCCESS]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_SUCCESS_1]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_SUCCESS_2]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_FAILED]: '#EF6260',
  [EXCHANGE_INNER_STATUS_CONFIRM_SUCCESS]: '#41CC9E',
  [EXCHANGE_INNER_STATUS_CONFIRM_FAILED]: '#EF6260',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY]: '#FF991F',
  [EXCHANGE_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_RETURN_STORAGE]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_RETURN_STORAGE]: '#FF991F',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_DELIVERY]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_DELIVERY]: '#FF991F',
  [EXCHANGE_INNER_STATUS_SUPPLIER_NOT_ADDED_LOGISTICS]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_SUPPLIER_UNCONFIRMED_LOGISTICS]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_DELIVERY]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_NOT_ADDED_REPLACE_STORAGE]: '#E63F3B',
  [EXCHANGE_INNER_STATUS_UNREVIEWED_REPLACE_STORAGE]: '#FF991F',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIVE]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_REPLACE_RECEIPT]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_UNCONFIRMED_FINISHED]: '#6C9CEB',
  [EXCHANGE_INNER_STATUS_FINISHED]: '#41CC9E',
}

// 退货明细内部状态
/**
 * 未确认发货
 */
export const MAIL_INNER_STATUS_UNCONFIRMED_DELIVER = 1
/**
 * 已确认发货
 */
export const MAIL_INNER_STATUS_CONFIRMED_DELIVER = 2
/**
 * 已确认收货
 */
export const MAIL_INNER_STATUS_CONFIRMED_RECEIVING = 3
/**
 * 确认回单
 */
export const MAIL_INNER_STATUS_CONFIRMED_BACK = 4

// 售后退货外部状态 StatusTag map
export const RETURN_OUTER_STATUS_TAG_MAP = {
  [RETURN_OUTER_STATUS_UNCOMMITTED]: 'default',
  [RETURN_OUTER_UNCONFIRMED]: 'primary',
  [RETURN_OUTER_STATUS_FAILED]: 'danger',
  [RETURN_OUTER_STATUS_SUCCESS]: 'primary',
  [RETURN_OUTER_STATUS_NOT_ADDED_RETURN_DELIVERY]: 'danger',
  [RETURN_OUTER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: 'warning',
  [RETURN_OUTER_STATUS_RETURN_DELIVERY]: 'danger',
  [RETURN_OUTER_STATUS_NOT_ADDED_RETURN_STORAGE]: 'danger',
  [RETURN_OUTER_STATUS_RETURN_RECEIVE]: 'danger',
  [RETURN_OUTER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: 'danger',
  [RETURN_OUTER_STATUS_TO_BE_REFUNDED]: 'danger',
  [RETURN_OUTER_STATUS_UNCONFIRMED_REFUNDED]: 'primary',
  [RETURN_OUTER_STATUS_NOT_RECEIVED]: 'warning',
  [RETURN_OUTER_STATUS_UNCONFIRMED_FINISHED]: 'primary',
  [RETURN_OUTER_STATUS_FINISHED]: 'success',
}

// 售后退货内部状态 Badge map
export const RETURN_INNER_STATUS_BADGE_MAP = {
  [RETURN_INNER_STATUS_UNCOMMITTED]: '#669EDE',
  [RETURN_INNER_STATUS_COMMIT_SUCCESS]: '#41CC9E',
  [RETURN_INNER_STATUS_SUCCESS_1]: '#41CC9E',
  [RETURN_INNER_STATUS_SUCCESS_2]: '#41CC9E',
  [RETURN_INNER_STATUS_FAILED_2]: '#EF6260',
  [RETURN_INNER_STATUS_CONFIRM_SUCCESS]: '#41CC9E',
  [RETURN_INNER_STATUS_CONFIRM_FAILED]: '#EF6260',
  [RETURN_INNER_STATUS_NOT_ADDED_RETURN_DELIVERY]: '#E63F3B',
  [RETURN_INNER_STATUS_UNREVIEWED_RETURN_DELIVERY]: '#FF991F',
  [RETURN_INNER_STATUS_CONSUMER_NOT_ADDED_LOGISTICS]: '#E63F3B',
  [RETURN_INNER_STATUS_CONSUMER_UNCONFIRMED_LOGISTICS]: '#6C9CEB',
  [RETURN_INNER_STATUS_UNCONFIRMED_RETURN_DELIVERY]: '#6C9CEB',
  [RETURN_INNER_STATUS_NOT_ADDED_RETURN_STORAGE]: '#E63F3B',
  [RETURN_INNER_STATUS_UNREVIEWED_RETURN_STORAGE]: '#FF991F',
  [RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIVE]: '#6C9CEB',
  [RETURN_INNER_STATUS_UNCONFIRMED_RETURN_RECEIPT]: '#6C9CEB',
  [RETURN_INNER_STATUS_TO_BE_REFUNDED]: '#E63F3B',
  [RETURN_INNER_STATUS_UNCONFIRMED_REFUNDED]: '#6C9CEB',
  [RETURN_INNER_STATUS_REFUNDED_FAIL]: '#EF6260',
  [RETURN_INNER_STATUS_REFUNDED_SUCCESS]: '#41CC9E',
  [RETURN_INNER_STATUS_UNCONFIRMED_FINISHED]: '#6C9CEB',
  [RETURN_INNER_STATUS_FINISHED]: '#41CC9E',
}

// 退款内部状态
/**
 * 未退款
 */
export const REFUND_INNER_STATUS_NO_REFUND = 1
/**
 * 退款失败
 */
export const REFUND_INNER_STATUS_REFUND_FAILED = 2
/**
 * 退款成功
 */
export const REFUND_INNER_STATUS_REFUND_SUCCESS = 3

// 退款外部状态
/**
 * 未退款
 */
export const REFUND_OUTER_STATUS_NO_REFUND = 1
/**
 * 待确认退款
 */
export const REFUND_OUTER_STATUS_UNCONFIRMED_REFUND = 2
/**
 * 退款未到账
 */
export const REFUND_OUTER_STATUS_NOT_RECEIVED = 3
/**
 * 退款到账
 */
export const REFUND_OUTER_STATUS_RECEIVED = 4

// 退款外部状态 StatusTag map
export const REFUND_OUTER_STATUS_TAG_MAP = {
  [REFUND_OUTER_STATUS_NO_REFUND]: 'danger',
  [REFUND_OUTER_STATUS_UNCONFIRMED_REFUND]: 'primary',
  [REFUND_OUTER_STATUS_NOT_RECEIVED]: 'warning',
  [REFUND_OUTER_STATUS_RECEIVED]: 'success',
}

// 工作流相关
/**
 * 售后退货外部流转
 */
export const RETURN_GOODS_OUTER_DELIVERY = 18
/**
 * 售后换货外部流转
 */
export const EXCHANGE_GOODS_OUTER_DELIVERY = 20
/**
 * 售后换货手工发货
 */
export const EXCHANGE_GOODS_MANUAL_DELIVERY = 30
/**
 * 售后退货手工发货
 */
export const RETURN_GOODS_MANUAL_DELIVERY = 31
