import {
  MEMBER_INNER_STATUS_TO_BE_COMMIT,
  MEMBER_INNER_STATUS_COMMIT_NOT_PASSED,
  MEMBER_INNER_STATUS_TO_BE_VERIFY_STEP1,
  MEMBER_INNER_STATUS_VERIFY_STEP1_NOT_PASSED,
  MEMBER_INNER_STATUS_TO_BE_VERIFY_STEP2,
  MEMBER_INNER_STATUS_VERIFY_STEP2_NOT_PASSED,
  MEMBER_INNER_STATUS_TO_CONFIRM,
  MEMBER_INNER_STATUS_VERIFY_NOT_PASSED,
  MEMBER_INNER_STATUS_VERIFY_PASSED,
  MEMBER_OUTER_STATUS_TO_PLATFORM_VERIFY,
  MEMBER_OUTER_STATUS_PLATFORM_VERIFYING,
  MEMBER_OUTER_STATUS_PLATFORM_VERIFY_PASSED,
  MEMBER_OUTER_STATUS_PLATFORM_VERIFY_NOT_PASSED,
  MEMBER_OUTER_STATUS_DEPOSITING,
  MEMBER_OUTER_STATUS_DEPOSITORY_PASSED,
  MEMBER_OUTER_STATUS_DEPOSITORY_NOT_PASSED,
  MEMBER_OUTER_STATUS_MODIFYING,
  MEMBER_OUTER_STATUS_MODIFY_PASSED,
  MEMBER_OUTER_STATUS_MODIFY_NOT_PASSED,
  MEMBER_STATUS_NORMAL,
  MEMBER_STATUS_FROZEN,
  MEMBER_STATUS_READY_LOGOFF,
} from '@/constants/const/member'

export const STATUS_COLOR_MAP = {
  0: '#669EDE',
  1: '#41CC9E',
  2: '#EF6260',
}

export const STATUS_COLOR_TXT = {
  0: '待审核',
  1: '审核通过',
  2: '冻结',
}

// 会员状态 StatusTag map
export const MEMBER_STATUS_TAG_MAP = {
  [MEMBER_STATUS_NORMAL]: 'success',
  [MEMBER_STATUS_FROZEN]: 'default',
  [MEMBER_STATUS_READY_LOGOFF]: 'warnning',
}

// 会员外部状态 StatusTag map
export const MEMBER_OUTER_STATUS_TYPE = {
  [MEMBER_OUTER_STATUS_TO_PLATFORM_VERIFY]: 'default',
  [MEMBER_OUTER_STATUS_PLATFORM_VERIFYING]: 'warning',
  [MEMBER_OUTER_STATUS_PLATFORM_VERIFY_PASSED]: 'success',
  [MEMBER_OUTER_STATUS_PLATFORM_VERIFY_NOT_PASSED]: 'danger',
  [MEMBER_OUTER_STATUS_DEPOSITING]: 'warning',
  [MEMBER_OUTER_STATUS_DEPOSITORY_PASSED]: 'success',
  [MEMBER_OUTER_STATUS_DEPOSITORY_NOT_PASSED]: 'danger',
  [MEMBER_OUTER_STATUS_MODIFYING]: 'warning',
  [MEMBER_OUTER_STATUS_MODIFY_PASSED]: 'success',
  [MEMBER_OUTER_STATUS_MODIFY_NOT_PASSED]: 'danger',
}

// 会员内部状态 Tag badge map
export const MEMBER_INNER_STATUS_BADGE_COLOR = {
  [MEMBER_INNER_STATUS_TO_BE_COMMIT]: 'grey',
  [MEMBER_INNER_STATUS_COMMIT_NOT_PASSED]: 'red',
  [MEMBER_INNER_STATUS_TO_BE_VERIFY_STEP1]: 'orange',
  [MEMBER_INNER_STATUS_VERIFY_STEP1_NOT_PASSED]: 'red',
  [MEMBER_INNER_STATUS_TO_BE_VERIFY_STEP2]: 'orange',
  [MEMBER_INNER_STATUS_VERIFY_STEP2_NOT_PASSED]: 'red',
  [MEMBER_INNER_STATUS_TO_CONFIRM]: 'blue',
  [MEMBER_INNER_STATUS_VERIFY_NOT_PASSED]: 'red',
  [MEMBER_INNER_STATUS_VERIFY_PASSED]: 'green',
}
