/** 活动相关 */

/** 活动推荐 */
export const ACTIVITY_HOT = 'hot';

/** 活动-特价促销 */
export const ACTIVITY_SPECIALOFFER = 'specialOffer';

/** 直降促销 */
export const ACTIVITY_PLUMMET = 'plummet';

/** 折扣促销 */
export const ACTIVITY_DISCOUNT = 'discount';

/** 满量促销-满量减 */
export const ACTIVITY_FULLQUANTITYSUB = 'fullQuantitySub';

/** 满量促销--满量折  */
export const ACTIVITY_FULLQUANTITYDISCOUNT = 'fullQuantityDiscount';

/** 满额促销--满额减  */
export const ACTIVITY_FULLMONEYSUB = 'fullMoneySub'

/** 满额促销--满额折 */
export const ACTIVITY_FULLMONEYDISCOUNT = 'fullMoneyDiscount'

/** 赠送促销-赠送商品 */
export const ACTIVITY_GIVEPRODUCT = 'giveProduct'

/** 赠送促销-赠送优惠券 */
export const ACTIVITY_GIVECOUPON = 'giveCoupon'

/** 赠送促销-多件促销 */
export const ACTIVITY_MOREPIECE = 'morePiece'

/** 赠送促销-组合促销 */
export const ACTIVITY_COMBINATION = 'combination'

/** 赠送促销-拼团 */
export const ACTIVITY_GROUPPURCHASE = 'groupPurchase'

/** 砍价 */
export const ACTIVITY_BARGAIN = 'bargain'

/** 秒杀 */
export const ACTIVITY_SECKILL = 'secKill'

/** 换购-满额换购 */
export const ACTIVITY_FULLSWAP = 'fullSwap'

/** 换购-满额换购 */
export const ACTIVITY_BUYSWAP = 'buySwap'

/** 换购-预售 */
export const ACTIVITY_PRESALE = 'preSale'

/** 套餐 */
export const ACTIVITY_SETMEAL = 'setMeal';

/** 试用  */
export const ACTIVITY_ATTEMPT = 'attempt';

/** 活动类型ID */

/** 活动-特价促销 */
export const ACTIVITY_SPECIALOFFER_NUMBER = 1;

/** 直降促销 */
export const ACTIVITY_PLUMMET_NUMBER = 2;

/** 折扣促销 */
export const ACTIVITY_DISCOUNT_NUMBER = 3;

/** 满量促销-满量减, minType: 1 */
export const ACTIVITY_FULLQUANTITYSUB_NUMBER = 4;

/** 满量促销--满量折 minType: 2 */
export const ACTIVITY_FULLQUANTITYDISCOUNT_NUMBER = 4;

/** 满额促销--满额减 minType: 1  */
export const ACTIVITY_FULLMONEYSUB_NUMBER = 5

/** 满额促销--满额折 minType: 2 */
export const ACTIVITY_FULLMONEYDISCOUNT_NUMBER = 5

/** 赠送促销-赠送商品 minType: 1 */
export const ACTIVITY_GIVEPRODUCT_NUMBER = 6

/** 赠送促销-赠送优惠券  minType: 2  */
export const ACTIVITY_GIVECOUPON_NUMBER = 6

/** 赠送促销-多件促销 */
export const ACTIVITY_MOREPIECE_NUMBER = 7

/** 赠送促销-组合促销 */
export const ACTIVITY_COMBINATION_NUMBER = 8

/** 拼团 */
export const ACTIVITY_GROUPPURCHASE_NUMBER = 9

/** 砍价 */
export const ACTIVITY_BARGAIN_NUMBER = 11

/** 秒杀 */
export const ACTIVITY_SECKILL_NUMBER = 12

/** 换购-满额换购 minType = 1 */
export const ACTIVITY_FULLSWAP_NUMBER = 13

/** 换购-满额换购 minType = 2  */
export const ACTIVITY_BUYSWAP_NUMBER = 13

/** 换购-预售 */
export const ACTIVITY_PRESALE_NUMBER = 14

/** 套餐 */
export const ACTIVITY_SETMEAL_NUMBER = 15;

/** 试用  */
export const ACTIVITY_ATTEMPT_NUMBER = 16;


export const ACTIVITY_LIST = [
  ACTIVITY_HOT,
  ACTIVITY_SPECIALOFFER,
  ACTIVITY_PLUMMET,
  ACTIVITY_DISCOUNT,
  ACTIVITY_FULLQUANTITYSUB,
  ACTIVITY_FULLQUANTITYDISCOUNT,
  ACTIVITY_FULLMONEYSUB,
  ACTIVITY_FULLMONEYDISCOUNT,
  ACTIVITY_GIVEPRODUCT,
  ACTIVITY_GIVECOUPON,
  ACTIVITY_MOREPIECE,
  ACTIVITY_COMBINATION,
  ACTIVITY_GROUPPURCHASE,
  ACTIVITY_BARGAIN,
  ACTIVITY_SECKILL,
  ACTIVITY_FULLSWAP,
  ACTIVITY_BUYSWAP,
  ACTIVITY_PRESALE,
  ACTIVITY_SETMEAL,
  ACTIVITY_ATTEMPT
] as const


export const ACTIVITY_NAME_TO_NUMBER = {
  [ACTIVITY_SPECIALOFFER]: ACTIVITY_SPECIALOFFER_NUMBER,
  [ACTIVITY_PLUMMET]: ACTIVITY_PLUMMET_NUMBER,
  [ACTIVITY_DISCOUNT]: ACTIVITY_DISCOUNT_NUMBER,
  [ACTIVITY_FULLQUANTITYSUB]: ACTIVITY_FULLQUANTITYSUB_NUMBER,
  [ACTIVITY_FULLQUANTITYDISCOUNT]: ACTIVITY_FULLQUANTITYDISCOUNT_NUMBER,
  [ACTIVITY_FULLMONEYSUB]: ACTIVITY_FULLMONEYSUB_NUMBER,
  [ACTIVITY_FULLMONEYDISCOUNT]: ACTIVITY_FULLMONEYDISCOUNT_NUMBER,
  [ACTIVITY_GIVEPRODUCT]: ACTIVITY_GIVEPRODUCT_NUMBER,
  [ACTIVITY_GIVECOUPON]: ACTIVITY_GIVECOUPON_NUMBER,
  [ACTIVITY_MOREPIECE]: ACTIVITY_MOREPIECE_NUMBER,
  [ACTIVITY_COMBINATION]: ACTIVITY_COMBINATION_NUMBER,
  [ACTIVITY_GROUPPURCHASE]: ACTIVITY_GROUPPURCHASE_NUMBER,
  [ACTIVITY_BARGAIN]: ACTIVITY_BARGAIN_NUMBER,
  [ACTIVITY_SECKILL]: ACTIVITY_SECKILL_NUMBER,
  [ACTIVITY_FULLSWAP]: ACTIVITY_FULLSWAP_NUMBER,
  [ACTIVITY_BUYSWAP]: ACTIVITY_BUYSWAP_NUMBER,
  [ACTIVITY_PRESALE]: ACTIVITY_PRESALE_NUMBER,
  [ACTIVITY_SETMEAL]: ACTIVITY_SETMEAL_NUMBER,
  [ACTIVITY_ATTEMPT]: ACTIVITY_ATTEMPT_NUMBER
}


